name: Verify Build

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install tools
      run: |
        sudo apt -y update
        sudo apt -y install gcc-arm-none-eabi
        sudo apt -y install python3-sphinx
    - name: Initialize Submodules
      run: git submodule update --init --recursive
    - name: clean
      run: make clean
    - name: make stm32f413
      run: make stm32f413
