name: Verify Build

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Initialize Submodules
      run: git submodule update --init --recursive
    - name: Install tools
      run: |
        sudo ./Embedded-Sharepoint/docker-start.sh -i
        docker build Embedded-Sharepoint/Dockerfile 
        docker compose -f Embedded-Sharepoint/docker-compose.yml build
        docker compose -f Embedded-Sharepoint/docker-compose.yml run --rm dev
        sudo apt -y update
    - name: clean
      run: make clean
    - name: make leader
      run: make leader
