name: Verify Build

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install tools
      run: |
        sudo apt -y update
        sudo apt -y install gcc-arm-none-eabi
    - name: Checkout submodules
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: clean
      run: make clean
    - name: make stm32f413
      run: make stm32f413
